python cli_vanilla.py fit \
    --data.num_tasks 1 \
    --data.current_task 0 \
    --data.val_split 0.2 \
    --data.max_length 77 \
    --data.batch_size 128 \
    --data.num_workers 8 \
    --data.config config.yaml \
    --data.dataset_name flickr30k \
    --data.root_dir ../artifacts/flickr-30k:v0\
    --model.model_name RN50 \
    --model.projection_dims 1024 \
    --model.temperature 0.1 \
    --model.lr 1e-5 \
    --model.lr_warmup_epochs 5 \
    --model.weight_decay 0.1 \
    --model.download_root ./ \
    --trainer.accelerator npu \
    --trainer.max_epochs 40 \
    --trainer.log_every_n_steps 1 \
    --trainer.logger WandbLogger \
    --trainer.logger.project CLIP-DIL-OpenAI \
    --trainer.logger.name RN50-vanilla \
    --trainer.logger.log_model False \
    --lr_monitor.logging_interval epoch \
    --model_checkpoint.dirpath ckpt \
    --model_checkpoint.save_weights_only True \
    --model_checkpoint.filename  RN50-vanilla