python cli_vanilla.py fit \
    --data.num_tasks 1 \
    --data.current_task 0 \
    --data.max_length 77 \
    --data.batch_size 256 \
    --data.num_workers 8 \
    --data.config config.yaml \
    --data.dataset_name cub200 \
    --data.root_dir /ppio_net0/torch_ds/cub200 \
    --model.model_name RN50 \
    --model.projection_dims 1024 \
    --model.temperature 0.1 \
    --model.lr 1e-4 \
    --model.lr_warmup_epochs 5 \
    --model.weight_decay 0.2 \
    --model.download_root ./ \
    --trainer.accelerator gpu \
    --trainer.precision 16 \
    --trainer.max_epochs 40 \
    --trainer.log_every_n_steps 1 \
    --trainer.logger WandbLogger \
    --trainer.logger.project CLIP-cub200 \
    --trainer.logger.name RN50-vanilla-pretrain \
    --trainer.logger.log_model False \
    --lr_monitor.logging_interval epoch \
    --model_checkpoint.dirpath ckpt \
    --model_checkpoint.save_weights_only True \
    --model_checkpoint.filename  RN50-vanilla-pretrain