python clip_cli_distill_cassle.py fit \
    --data.num_tasks 1 \
    --data.current_task 0 \
    --data.val_split 0.2 \
    --data.max_length 77 \
    --data.batch_size 32 \
    --data.num_workers 8 \
    --data.config config.yaml \
    --data.dataset_name flickr30k \
    --data.root_dir ../artifacts/flickr-30k:v0\
    --model.model_name RN50 \
    --model.projection_dims 1024 \
    --model.temperature 0.1 \
    --model.lr 1e-3 \
    --model.weight_decay 1e-6 \
    --model.download_root ./ \
    --trainer.accelerator gpu \
    --trainer.precision 16 \
    --trainer.max_epochs 40 \
    --trainer.log_every_n_steps 1 \
    --trainer.logger WandbLogger \
    --trainer.logger.project CLIP-DIL-OpenAI \
    --trainer.logger.name RN50-bs256-distill-cassle \
    --trainer.logger.log_model False \
    --trainer.strategy ddp_find_unused_parameters_true \
    --lr_monitor.logging_interval epoch \
    --model_checkpoint.dirpath ckpt \
    --model_checkpoint.save_weights_only True \
    --model_checkpoint.filename  RN50-bs256-distill-cassle