python image_retrieval/cli.py fit \
    --data.dataset_name flickr8k \
    --data.artifact_id wandb/clip.lightning-image_retrieval/flickr-8k:latest \
    --model.image_encoder_alias resnet18 \
    --model.text_encoder_alias distilbert-base-uncased \
    --model.image_embedding_dims 512 \
    --model.image_encoder_lr 0.0001 \
    --model.image_encoder_pretrained true \
    --model.image_encoder_trainable true \
    --model.projection_dims 512 \
    --model.image_encoder_lr 0.0001 \
    --trainer.accelerator gpu \
    --trainer.max_epochs 20 \
    --trainer.log_every_n_steps 1 \
    --trainer.logger WandbLogger \
    --trainer.logger.project CLIP \
    --trainer.logger.log_model all \
    --lr_monitor.logging_interval step